---
# Shared prepare playbook for all molecule scenarios.
- name: Prepare instance
  hosts: all
  gather_facts: false

  tasks:
    - name: Start user systemd instance
      ansible.builtin.systemd:
        name: "user@0.service"
        state: started
